version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.0-apache
    steps:
      - checkout
      - run: sudo apt upgrade
      - run: sudo docker-php-ext-install zip
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: composer install -n --prefer-dist
  test:
    docker:
      - image: circleci/php:7.3.0-apache
    steps:
      - ~/./vendor/bin/phpunit tests --color
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
